config/routes.rb
Vivatjesus::Application.routes.draw do

  resources :payments

  match '/calendar' => 'pages#calendar'

  match '/posts/rss' => 'posts#rss'
  match '/events/rss' => 'events#rss'
  match '/password/:id' => 'users#password'

  
  get "errors/404"
  get "errors/500"

  match "/signin" => "sessions#signin"
  match "/signout" => "sessions#signout"

  match '/auth/:service/callback' => 'sessions#create' 
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider' => "application#omniauth"
  match '/feed' => "users#feed"
  match '/activity' => "users#allfeed"
  match '/councilfeed' => "users#councilfeed"
  match '/activity/:id' => "users#showfeed"
  match '/twitter' => "users#twitter"
  match '/facebook' => "users#facebook"
  match '/deauthtwitter' => "users#deauthtwitter"
  match '/deauthfacebook' => "users#deauthfacebook"

  match ':user/following' => 'follows#index', :view => 'following', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  match ':user/followers' => 'follows#index', :view => 'followers', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  match '/users/pollallfeed' => 'users#pollallfeed'
  match '/users/pollfeed' => 'users#pollfeed'
  match '/users/polluserfeed/:userid' => 'users#polluserfeed'
  match '/statuses/pollfeed' => 'statuses#pollfeed'
  match '/follows/block/:id' => 'follows#block'
  match '/follows/unblock/:id' => 'follows#unblock'
  

  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/about' => 'pages#about'
  match '/aboutus' => 'pages#aboutus'
  match '/join' => 'pages#join'
  match '/pages/contact' => 'pages#contact'
  match '/search' => 'posts#search'
  match '/news' => 'pages#news'
  match '/success' => 'pages#success'
  match '/users/password' => "users#password"
  match ':user/edit' => 'users#edit'
  match 'search/:username' => 'users#search'

  match '/mobile' => 'mobile#index'
  match '/mobile/home' => 'mobile#index'
  match '/mobile/about' => 'mobile#about'
  match '/mobile/news' => 'mobile#news'
  match '/mobile/calendar' => 'mobile#calendar'
  match '/mobile/menu' => 'mobile#menu'
  match '/mobile/timeline' => 'mobile#timeline'
  match '/mobile/post/:id' => 'mobile#post'

  match 'fetchfeeds' => 'posts#fetchfeeds'

  resources :events
  resources :posts
  resources :users
  resources :sessions
  resources :password_resets
  resources :sponsors
  resources :councils
  resources :statuses
  resources :follows
  

  match ':user' => 'users#show', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  
  match '*a', :to => 'errors#404'

  root :to => 'pages#index'

end

app/models/council.rb
class Council < ActiveRecord::Base
  has_many :users
  has_many :payments
  has_many :activities
end

app/controllers/councils_controller.rb
class CouncilsController < ApplicationController
  before_filter :admin_required  
  before_filter :current_council  

  # GET /councils
  # GET /councils.json
  def index
    
    if @current_user.id == 1
      @councils = Council.find(:all, :order => 'councilnumber')
    else  
      @councils = Council.find(:all, :conditions => ['id = ?', @current_user.council_id], :order => 'councilnumber')
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @councils }
    end
  end

  # GET /councils/1
  # GET /councils/1.json
  def show
    @council = Council.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @council }
    end
  end

  # GET /councils/new
  # GET /councils/new.json
  def new
    if @current_user.id == 1
      @council = Council.new
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @council }
    end
  end

  # GET /councils/1/edit
  def edit
    @council = Council.find(params[:id])
  end

  # POST /councils
  # POST /councils.json
  def create
    
    if @current_user.id == 1
      @council = Council.new(params[:council])
    end

    respond_to do |format|
      if @council.save
        format.html { redirect_to @council, :notice => 'Council was successfully created.' }
        format.json { render :json => @council, :status => :created, :location => @council }
      else
        format.html { render :action => "new" }
        format.json { render :json => @council.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /councils/1
  # PUT /councils/1.json
  def update
    @council = Council.find(params[:id])

    respond_to do |format|
      if @council.update_attributes(params[:council])
        format.html { redirect_to @council, :notice => 'Council was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @council.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /councils/1
  # DELETE /councils/1.json
  def destroy
    
    if @current_user.id == 1
      @council = Council.find(params[:id])
      @council.destroy
    end
    
    respond_to do |format|
      format.html { redirect_to councils_url }
      format.json { head :ok }
    end
  end
end

app/helpers/councils_helper.rb
module CouncilsHelper
end

app/views/councils/_form.html.erb
<div id="generalform">
<%= form_for(@council) do |f| %>
  <% if @council.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@council.errors.count, "error") %> prohibited this council from being saved:</h2>

      <ul>
      <% @council.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Council Name*" %><%= f.text_field :councilname, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "Council Number*" %><%= f.text_field :councilnumber, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "Council email address*" %><%= f.text_field :email, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "State's Website URL*" %><%= f.text_field :stateurl, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "Posterous URL* (used for automating posts via email)" %><%= f.text_field :posterousurl, :class=>"input-xxlarge" %>
  </div> 
  <div class="field">
    <%= f.label "Google Calendar Embedcode* (used for calendar page)" %>
    i.e. http://www.google.com/calendar/embed?title=Knights%20of%20Columbus%20Council%2010062&amp;height=600&amp;wkst=1&amp;bgcolor=%233366ff&amp;src=tpg0ni9rp7mdkrdsfarnvi1oqk%40group.calendar.google.com&amp;color=%23AB8B00&amp;ctz=America%2FPhoenix
	<%= f.text_field :calendarurl, :class=>"input-xxlarge" %>
  </div>
  <!-- <div class="field">
    <%# f.label "Posterous Newsfeed URL* (used for News page)." %>
	Feedburner recommended (i.e. http://feeds.feedburner.com/TheKnightsOfColumbus10062)
	<%# f.text_field :newsurl, :class=>"input-xxlarge" %>
  </div> -->
  <div class="field">
    <%= f.label "About Us Description* (used on home page and about us page)" %><%= f.text_area :about, :class=>"input-xxlarge" %>
  </div>

  <div class="field">
    <%= f.label "Twitter URL (optional)" %><%= f.text_field :twitterurl, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "Facebook URL (optional)" %><%= f.text_field :facebookurl, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "LinkedIn URL (optional)" %><%= f.text_field :linkedinurl, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "Google Plus URL (optional)" %><%= f.text_field :googleplusurl, :class=>"input-xxlarge" %>
  </div>
<!--   <div class="field">
    <%= f.label "Mobile App URL (optional)" %><%# f.text_field :mobileurl, :class=>"input-xxlarge" %>
  </div>
 -->
  <div>
    <p><%= f.submit "Submit", :class=>"btn  btn-primary btn-large" %></p>
  </div>
<% end %>
</div>

app/views/councils/edit.html.erb
<div class="hero-unit">
	<h1>Editing Council</h1><br />

<%= render 'form' %>

<%= link_to 'Show', @council %> |
<%= link_to 'Back', councils_path %>
</div>

app/views/councils/index.html.erb
<div class="hero-unit">
	<h1>Listing Councils</h1><br />

<table class="table table-striped">
  <tr>
    <th>Councilname</th>
    <th>Councilnumber</th>
    <th>Twitterurl</th>
    <th>Facebookurl</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @councils.each do |council| %>
  <tr>
    <td><%= council.councilname %></td>
    <td><%= council.councilnumber %></td>
    <td><%= council.twitterurl %></td>
    <td><%= council.facebookurl %></td>
    <td><%= council.email %></td>
    <td><%= link_to 'Show', council %></td>
    <td><%= link_to 'Edit', edit_council_path(council) %></td>
    <td><%= link_to 'Destroy', council, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% if @current_user.id == 1 %>
<%= link_to 'New Council', new_council_path %>
<% end %>

</div>

app/views/councils/new.html.erb
<div class="hero-unit">
	<h1>New Council</h1><br />

<%= render 'form' %>

<%= link_to 'Back', councils_path %>
</div>

app/views/councils/show.html.erb
<div class="hero-unit">
	<p id="notice"><%= notice %></p>

<p>
  <b>Councilname:</b>
  <%= @council.councilname %>
</p>

<p>
  <b>Councilnumber:</b>
  <%= @council.councilnumber %>
</p>


<p>
  <b>Email:</b>
  <%= @council.email %>
</p>

<p>
  <b>State Website:</b>
  <%= @council.stateurl %>
</p>

<p>
  <b>Posterousurl:</b>
  <%= @council.posterousurl %>
</p>

<p>
  <b>Calendarurl:</b>
  <%= @council.calendarurl %>
</p>

<p>
  <b>About:</b>
  <%= @council.about %>
</p>
<p>
  <b>Twitterurl:</b>
  <%= @council.twitterurl %>
</p>

<p>
  <b>Facebookurl:</b>
  <%= @council.facebookurl %>
</p>

<p>
  <b>Linkedinurl:</b>
  <%= @council.linkedinurl %>
</p>

<p>
  <b>Googleplusurl:</b>
  <%= @council.googleplusurl %>
</p>



<%= link_to 'Edit', edit_council_path(@council) %> |
<%= link_to 'Back', councils_path %>

</div>