config/routes.rb
Vivatjesus::Application.routes.draw do

  resources :payments

  match '/calendar' => 'pages#calendar'

  match '/posts/rss' => 'posts#rss'
  match '/events/rss' => 'events#rss'
  match '/password/:id' => 'users#password'

  
  get "errors/404"
  get "errors/500"

  match "/signin" => "sessions#signin"
  match "/signout" => "sessions#signout"

  match '/auth/:service/callback' => 'sessions#create' 
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider' => "application#omniauth"
  match '/feed' => "users#feed"
  match '/activity' => "users#allfeed"
  match '/councilfeed' => "users#councilfeed"
  match '/activity/:id' => "users#showfeed"
  match '/twitter' => "users#twitter"
  match '/facebook' => "users#facebook"
  match '/deauthtwitter' => "users#deauthtwitter"
  match '/deauthfacebook' => "users#deauthfacebook"

  match ':user/following' => 'follows#index', :view => 'following', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  match ':user/followers' => 'follows#index', :view => 'followers', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  match '/users/pollallfeed' => 'users#pollallfeed'
  match '/users/pollfeed' => 'users#pollfeed'
  match '/users/polluserfeed/:userid' => 'users#polluserfeed'
  match '/statuses/pollfeed' => 'statuses#pollfeed'
  match '/follows/block/:id' => 'follows#block'
  match '/follows/unblock/:id' => 'follows#unblock'
  

  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/about' => 'pages#about'
  match '/aboutus' => 'pages#aboutus'
  match '/join' => 'pages#join'
  match '/pages/contact' => 'pages#contact'
  match '/search' => 'posts#search'
  match '/news' => 'pages#news'
  match '/success' => 'pages#success'
  match '/users/password' => "users#password"
  match ':user/edit' => 'users#edit'
  match 'search/:username' => 'users#search'

  match '/mobile' => 'mobile#index'
  match '/mobile/home' => 'mobile#index'
  match '/mobile/about' => 'mobile#about'
  match '/mobile/news' => 'mobile#news'
  match '/mobile/calendar' => 'mobile#calendar'
  match '/mobile/menu' => 'mobile#menu'
  match '/mobile/timeline' => 'mobile#timeline'
  match '/mobile/post/:id' => 'mobile#post'

  match 'fetchfeeds' => 'posts#fetchfeeds'

  resources :events
  resources :posts
  resources :users
  resources :sessions
  resources :password_resets
  resources :sponsors
  resources :councils
  resources :statuses
  resources :follows
  

  match ':user' => 'users#show', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  
  match '*a', :to => 'errors#404'

  root :to => 'pages#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :follow_id, :message, :register_id, :status_id, :user_id
  has_many :statuses
  has_many :contacts
  belongs_to :user
  belongs_to :council
end

app/models/council.rb
class Council < ActiveRecord::Base
  has_many :users
  has_many :payments
  has_many :activities
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
  belongs_to :user
  def self.per_page
    3
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  attr_accessible :block_id, :follow_id, :user_id
  belongs_to :user
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :council_id, :description, :paypalcode, :promoactive, :title
  belongs_to :council
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  def self.per_page
    3
  end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :location, :message, :mylat, :mylong, :user_id
  attr_protected :twitter
  attr_protected :facebook
  
  belongs_to :user
  belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :username, :email, :password, :password_confirmation
  has_secure_password
  # validates_uniqueness_of :username, :on => :create  
  validates :username, :presence =>true,
                      :uniqueness=>true, :on => :create
  validates_format_of :username, :with => /^[A-Za-z\d_]+$/,
                      :message => "can only contain letters and numbers (no spaces)."                      
  validates :fullname, :presence =>true,
                      :uniqueness=>true, :on => :create 
  validates :email, :presence =>true,
                      :uniqueness=>true, :on => :create 
  validates :password, :presence =>true,
                      :length => { :minimum => 5, :maximum => 40 },
                      :confirmation =>true, :on => :create 
  has_many :posts
  has_many :events
  belongs_to :council
  has_many :follows
  has_many :statuses
  has_many :activities

  before_create { generate_token(:auth_token) }
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver #rescue ""
  end

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  
  before_filter :current_user  
  before_filter :current_council  
  
  # GET /sponsors
  # GET /sponsors.json
  def index
    
    if @current_user
      @sponsors = Sponsor.order("sponsorname").where("council_id = ?",  @current_user.council_id)
    else
      @sponsors = Sponsor.order("sponsorname").where("council_id = ?", @council.id)
    end
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.json
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(params[:sponsor])

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render json: @sponsor, status: :created, location: @sponsor }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.json
  def update
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/councils_helper.rb
module CouncilsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @current_user %>
	<%= f.hidden_field :council_id, :value => @current_user.council_id %>
  <% else %>
	<%= f.hidden_field :council_id, :value => @council.id %>
  <% end %>

  <%= f.hidden_field :council_id, :value => @council.id %>
  <div class="field">
    <%= f.text_field :sponsorname, :autofocus => true, :class=>"input-xxlarge", :autofocus => true, :placeholder=>"Spondor name" %>
  </div>
  <div class="field">
    <%= f.text_field :url, :class=>"input-xxlarge", :placeholder=>"Spondor website" %>
  </div>
  <div class="field">
    <%= f.text_area :description, :class=>"input-xxlarge", :placeholder=>"Spondor descrtiption" %>
  </div>
  <div>
    <p><%= f.submit "Submit", :class=>"btn  btn-primary btn-large" %></p>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<div class="hero-unit">
<h1>Editing Sponsor</h1><br />

<%= render 'form' %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>
</div>

app/views/sponsors/index.html.erb
<div class="hero-unit">
	<h1>Our Sponsors</h1><br />

<table class="table table-striped">

<% @sponsors.each do |sponsor| %>
  <tr>
    <td><a href="<%= sponsor.url %>"><%= sponsor.sponsorname %></a></td>
    <td><%= sponsor.description %></td>
    <td>
<% if @current_user && @current_user.publisher %>
	<%= link_to 'Show', sponsor %> | 
    <%= link_to 'Edit', edit_sponsor_path(sponsor) %> | 
    <%= link_to 'Destroy', sponsor, confirm: 'Are you sure?', method: :delete %>
<% end %>
</td>
  </tr>
<% end %>
</table>

<br />

<% if @current_user && @current_user.publisher %>
	<%= link_to 'New Sponsor', new_sponsor_path %>
<% end %>
</div>

app/views/sponsors/new.html.erb
<div class="hero-unit">
	<h1>New Sponsor</h1><br />

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>
</div>

app/views/sponsors/show.html.erb
<div class="hero-unit">
	<p id="notice"><%= notice %></p>

<p>
  <b>Sponsorname:</b>
  <%= @sponsor.sponsorname %>
</p>

<p>
  <b>Url:</b>
  <%= @sponsor.url %>
</p>

<p>
  <b>Description:</b>
  <%= @sponsor.description %>
</p>


<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>
</div>