config/routes.rb
Vivatjesus::Application.routes.draw do

  resources :payments

  match '/calendar' => 'pages#calendar'

  match '/posts/rss' => 'posts#rss'
  match '/events/rss' => 'events#rss'
  match '/password/:id' => 'users#password'

  
  get "errors/404"
  get "errors/500"

  match "/signin" => "sessions#signin"
  match "/signout" => "sessions#signout"

  match '/auth/:service/callback' => 'sessions#create' 
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider' => "application#omniauth"
  match '/feed' => "users#feed"
  match '/activity' => "users#allfeed"
  match '/councilfeed' => "users#councilfeed"
  match '/activity/:id' => "users#showfeed"
  match '/twitter' => "users#twitter"
  match '/facebook' => "users#facebook"
  match '/deauthtwitter' => "users#deauthtwitter"
  match '/deauthfacebook' => "users#deauthfacebook"

  match ':user/following' => 'follows#index', :view => 'following', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  match ':user/followers' => 'follows#index', :view => 'followers', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  match '/users/pollallfeed' => 'users#pollallfeed'
  match '/users/pollfeed' => 'users#pollfeed'
  match '/users/polluserfeed/:userid' => 'users#polluserfeed'
  match '/statuses/pollfeed' => 'statuses#pollfeed'
  match '/follows/block/:id' => 'follows#block'
  match '/follows/unblock/:id' => 'follows#unblock'
  

  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/about' => 'pages#about'
  match '/aboutus' => 'pages#aboutus'
  match '/join' => 'pages#join'
  match '/pages/contact' => 'pages#contact'
  match '/search' => 'posts#search'
  match '/news' => 'pages#news'
  match '/success' => 'pages#success'
  match '/users/password' => "users#password"
  match ':user/edit' => 'users#edit'
  match 'search/:username' => 'users#search'

  match '/mobile' => 'mobile#index'
  match '/mobile/home' => 'mobile#index'
  match '/mobile/about' => 'mobile#about'
  match '/mobile/news' => 'mobile#news'
  match '/mobile/calendar' => 'mobile#calendar'
  match '/mobile/menu' => 'mobile#menu'
  match '/mobile/timeline' => 'mobile#timeline'
  match '/mobile/post/:id' => 'mobile#post'

  match 'fetchfeeds' => 'posts#fetchfeeds'

  resources :events
  resources :posts
  resources :users
  resources :sessions
  resources :password_resets
  resources :sponsors
  resources :councils
  resources :statuses
  resources :follows
  

  match ':user' => 'users#show', :constraints => { :user => /[0-9A-Za-z\-\_\@\.\%20]+/ }
  
  match '*a', :to => 'errors#404'

  root :to => 'pages#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :council_id, :description, :paypalcode, :promoactive, :title
  belongs_to :council
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  
  before_filter :admin_required, :except => [:index]
  
  before_filter :current_user  
  before_filter :current_council  
  

  # GET /payments
  # GET /payments.json
  def index
    
    if @current_user
      @payments = Payment.find(:all, :conditions => ['council_id = ?', @current_user.council_id], :order => 'title')
    else
      @payments = Payment.find(:all, :conditions => ['council_id = ?', @council.id], :order => 'title')
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    
    if @current_user.council_id == @payment.council_id or @current_user.admin    
      @payment.destroy
    end 

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @current_user %>
	<%= f.hidden_field :council_id, :value => @current_user.council_id %>
	<% @councilnumber = @current_user.council.councilnumber %>
  <% else %>
	<%= f.hidden_field :council_id, :value => @council.id %>
	<% @councilnumber = @council.councilnumber %>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :autofocus => true, :class=>"input-xxlarge focus", :placeholder=>"Title of Promo" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class=>"input-xxlarge", :placeholder=>"Description" %>
  </div>
  <div class="field">
    <%= f.label :paypalcode %>
	Please direct your PayPal success page to http://<%=@councilnumber%>.vivatjes.us/success<br />
    <%= f.text_area :paypalcode, :class=>"input-xxlarge", :placeholder=>"PayPal-supplied code" %>
  </div>
  <div class="field">
    <%= f.label :promoactive %> 
    <%= f.check_box :promoactive %>
  </div>
  <div><br />
    <%= f.submit :class=>"btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment Option</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<div class="hero-unit">
	<h1>Now Accepting Online Payments</h1>
	<br />
	<!-- <img src="/images/logo-paypal.jpg" align="right" width="250"> -->
	<%= image_tag("logo-paypal.jpg", :align=>"right", :width=>"250")%>
	
	<p>
		<% if @current_user %>
			<% @councilnumber = @current_user.council.councilnumber %>
		<% elsif @council %>
			<% @councilnumber = @council.councilnumber %>
		<% else %>
			<% @councilnumber = "" %>
		<% end %>

		The Knights of Columbus council <%= @councilnumber %> is now accepting payments online for raffle tickets, sponsor donations, annual dues, etc.   
	</p>

	<p>

<% if @payments.length > 0 %>
	
	<% @payments.each do |payment| %>

	<% if payment.promoactive or (@current_user && @current_user.admin) %>
	<div class="row-fluid">
		<div class="span8">
			<h2>
				<%= payment.title %>
				<% if !payment.promoactive %>
					<span style="color:red;">NOT ACTIVE</span>
				<% end %>
			</h2>
			<p><%= payment.description %></p>
			<p>
				<% if @current_user && @current_user.admin %>
				    <%= link_to 'Show', payment %>
				    <%= link_to 'Edit', edit_payment_path(payment) %>
				    <%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</p>
		</div>

		<div class="span4">
			<p><%= raw(payment.paypalcode) %></p>
		</div>
	</div>
	<% end %>

	<% end %>

<% else %>
	No active promotions available...<br /><br />
<% end %>

<br />


</div>

<% if @current_user && @current_user.admin %>
<%= link_to 'New Payment', new_payment_path %>
<% end %>

app/views/payments/new.html.erb
<h1>New Payment Option</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Council:</b>
  <%= @payment.council_id %>
</p>

<p>
  <b>Title:</b>
  <%= @payment.title %>
</p>

<p>
  <b>Description:</b>
  <%= @payment.description %>
</p>

<p>
  <b>Paypalcode:</b>
  <%= @payment.paypalcode %>
</p>

<p>
  <b>Promoactive:</b>
  <%= @payment.promoactive %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>